# Namespace da app-a
apiVersion: v1
kind: Namespace
metadata:
  name: app-a
---
# Deployment da app-a
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  namespace: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
---
# Service da app-a
apiVersion: v1
kind: Service
metadata:
  name: app-a
  namespace: app-a
spec:
  selector:
    app: app-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
